
version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  employee-service:
    build: ./employee-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo

  payroll-service:
    build: ./payroll-service
    ports:
      - "4002:4002"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - employee-service
      - payroll-service

volumes:
  mongo-data:
